// =====================================================================
// DJ24 XD — "The Z Story"  (PeteZDj)
// A music RPG / open-world story campaign set on Planet Ongaku.
// 101 episodes across 5 acts. Rewards scale up each act.
// This is the data backbone consumed by MissionsPage + MissionPage.
// Design docs live in /content/game/*.md
// =====================================================================

export const gameMeta = {
  title: 'DJ24 XD',
  subtitle: 'The Z Story',
  tagline: 'Rise from nobody to the villain of the whole sound.',
  cover: '/images/game/game-cover.png',
  episodeCount: 101,
  blurb:
    'A create-your-own-character music RPG. Build your DJ from nothing, throw house parties, ' +
    'jack the beats, run the streets, and climb four regions of Planet Ongaku — Flowers, Hearts, ' +
    'Diamonds and Spades — until the kid who wanted justice becomes the thing he was fighting.',
};

// ---- Acts (in play order). Each maps to a region, a "suit", and a reward tier. ----
export const acts = {
  prologue: {
    key: 'prologue', no: 0, name: 'Prologue', subtitle: 'The Pilot',
    suit: '◇', region: 'Hometown — a small city on Ongaku', color: '#a855f7',
    art: '/images/game/arc-prologue.png', rewardTier: '$0 – $2K',
    desc: 'One wild night out ends with a murder on live TV. The come-up begins with a funeral and a one-way ticket.',
  },
  flowers: {
    key: 'flowers', no: 1, name: 'Act I — Flowers', subtitle: 'The Come-Up',
    suit: '❀', region: 'Africa-inspired Ongaku (home turf)', color: '#f97316',
    art: '/images/game/arc-flowers.png', rewardTier: '$1K – $25K',
    desc: 'Back home and broke. Spin for rent, run with the D-Boys, and turn house parties into a name.',
  },
  hearts: {
    key: 'hearts', no: 2, name: 'Act II — Hearts', subtitle: 'Royal Music School',
    suit: '♥', region: 'Asia / Europe — the Royal Music School', color: '#ec4899',
    art: '/images/game/arc-hearts.png', rewardTier: '$20K – $150K',
    desc: 'A two-year scholarship among the elite. Duels, romance, rivals — and the first taste of the industry rot.',
  },
  diamonds: {
    key: 'diamonds', no: 3, name: 'Act III — Diamonds', subtitle: 'Billionaire X',
    suit: '♦', region: 'Middle-Eastern royalty & the music industry', color: '#eab308',
    art: '/images/game/arc-diamonds.png', rewardTier: '$100K – $1M',
    desc: 'Adopted by an empire of money. Private jets, royalty, and the deal that costs your soul.',
  },
  spades: {
    key: 'spades', no: 4, name: 'Act IV — Spades', subtitle: 'Regicide',
    suit: '♠', region: 'Ongaku Prime — the skyscraper capital', color: '#38bdf8',
    art: '/images/game/arc-spades.png', rewardTier: '$1M – $50M',
    desc: 'The final turn. Take the capital, end the king, and crown yourself the villain of the whole sound.',
  },
};

export const actOrder = ['prologue', 'flowers', 'hearts', 'diamonds', 'spades'];

// Helper to keep episode objects short.
function ep(no, act, title, giver, location, area, rewardCash, unlocks, featuring, objectives, synopsis, extra = {}) {
  return {
    no, act, title, giver, location, area, rewardCash,
    unlocks, featuring, objectives, synopsis,
    slug: `ep${String(no).padStart(3, '0')}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`,
    ...extra,
  };
}

export const episodes = [
  // ============================ PROLOGUE — THE PILOT ============================
  ep(1, 'prologue', 'In the Beginning', 'Blake', "Pete's apartment", 'Hometown',
    0, ['BMX', 'Hometown map'],
    ['Pete', 'Blake'],
    ['Finish the night-shift code build', 'Answer Blake’s call', 'Get ready to head out'],
    'A rave ends in chaos as paramedics work the floor; across town Pete is coding alone when Blake calls — get dressed, he’s on his way.',
    { boss: false, walkthrough:
      'The game opens cold on a packed rave where the bass has literally dropped people — paramedics give CPR under the strobes. ' +
      'Cut to PETE, our create-your-own protagonist, finishing a freelance programming job at his desk while streaming the same live set on his phone. ' +
      'His friend BLAKE calls: "Yo, get dressed, I’m on my way to scoop you." This is the tutorial: you learn movement, the phone menu, and how to get changed. ' +
      'Once you’re ready, the chapter ends and the night begins.' },
  ),
  ep(2, 'prologue', 'Sky the Crib', 'Blake', 'The Plug’s spot', 'Hometown',
    0, ['Plug contact', 'Buy: weed & booze'],
    ['Pete', 'Blake', 'The Plug'],
    ['Ride with Blake', 'Stop at the Plug', 'Stock up for the party'],
    'Blake skips the crib and detours to the plug to load up on weed and booze before the party — your first taste of the buy/consume systems.',
  ),
  ep(3, 'prologue', 'Street Race to the Party', 'Blake', 'ZDTV strip', 'Hometown',
    0, ['Street Racing minigame'],
    ['Pete', 'Blake', 'Ted'],
    ['Beat the rival crew across town', 'Don’t total the car', 'Arrive at the ZDTV Bass party'],
    'A red-light challenge turns into a full street race to the ZDTV Bass after-party, introducing the racing minigame.',
  ),
  ep(4, 'prologue', 'A Way Inside', 'Banda', 'The club line', 'Hometown',
    0, ['Bribe mechanic', 'Banda contact'],
    ['Pete', 'Blake', 'Banda', 'Marko'],
    ['Find a way past the bouncer', 'Run into Banda', 'Get the crew waved in'],
    'The line is impossible until Pete bumps into old friend Banda — now a rising DJ — who has a connect at the door.',
  ),
  ep(5, 'prologue', 'Sick Nightclub', null, 'The club floor', 'Hometown',
    0, ['Social: photos', 'Jack the Beats (intro)'],
    ['Pete', 'a Celebrity', 'Banda'],
    ['Get a photo with the celebrity', 'Win a bar fight', 'Talk your way toward the VIP'],
    'Inside: rich crowds, top-shelf liquor, and a celebrity worth a selfie — plus the first scuffle that teaches the fight system.',
  ),
  ep(6, 'prologue', 'Take the Decks', 'DJ UV', 'The DJ booth', 'Hometown',
    1000, ['Internship offer', 'Genre-switch (EDM mashup)'],
    ['Pete', 'DJ UV', 'Banda'],
    ['Convince the DJ to let you spin', 'Read the crowd', 'Drop the EDM mashup and send the room'],
    'Pete bluffs his way behind the decks, flips the genre into an EDM mashup, blows the roof off, and lands an internship offer.',
    { boss: false },
  ),
  ep(7, 'prologue', 'Faded Sunrise', null, 'City streets', 'Hometown',
    0, ['Hangover system', 'Drive-home (impaired)'],
    ['Pete', 'Blake'],
    ['Drive home faded at sunrise', 'Avoid the cops', 'Sneak into the house'],
    'Sunrise, dark glasses, a head full of last night — get home and sneak past a driveway full of cars you don’t recognise.',
  ),
  ep(8, 'prologue', 'The Broadcast', 'Mom', "Pete's family home", 'Hometown',
    0, ['Story flag: The Politician'],
    ['Pete', 'Mom', 'The Politician'],
    ['Talk to Mom', 'Watch the news bulletin', 'Recognise the man on TV'],
    'The cars were for a wake: Pete’s father-figure was gunned down — live on TV, by a smiling politician — and Pete realises he saw that man at the club.',
    { boss: false },
  ),
  ep(9, 'prologue', 'Number One', 'Sister', 'Hometown → Airport', 'Hometown',
    2000, ['Royal Music School (Hearts)', 'Air travel'],
    ['Pete', 'Sister', 'The Politician'],
    ['Climb the local chart to #1', 'Attend the funeral', 'Open the scholarship letter', 'Fly out'],
    'Grief turns to fuel: Pete blacklists his way to the city’s #1 set, buries his father, and opens a letter — a scholarship to the Royal Music School.',
    { boss: true },
  ),

  // ============================ ACT I — FLOWERS (THE COME-UP) ============================
  ep(10, 'flowers', 'Letter from Sister', 'Sister', 'Family home', 'Flowers — Home City',
    1000, ['Home base (Crib)'],
    ['Pete', 'Sister', 'Mom'],
    ['Settle back home', 'Read the family letter', 'Promise to send money'],
    'Before the school year starts, Pete is home in the Flowers region — everything looks fine on the surface, but the bills say otherwise.',
  ),
  ep(11, 'flowers', 'Meet Kyenks', 'Kyenks', 'Ciani Village', 'Flowers — Home City',
    1500, ['Crew slot: Kyenks'],
    ['Pete', 'Kyenks'],
    ['Find Kyenks at the market', 'Pass the rhythm test', 'Join his circle'],
    'Local fixer Kyenks takes Pete under his wing and shows him how music really moves money around here.',
  ),
  ep(12, 'flowers', 'Mom Goes Back to Work', 'Mom', 'Family home', 'Flowers — Home City',
    1500, ['Reputation: Family'],
    ['Pete', 'Mom'],
    ['Drive Mom to her shift', 'Cover the rent gap', 'Promise to handle it'],
    'Money is tight enough that Mom returns to work; Pete swears he’ll carry the household on music alone.',
  ),
  ep(13, 'flowers', 'Things Get Worse Quick', 'Kyenks', 'Back blocks', 'Flowers — Home City',
    2000, ['Stash house'],
    ['Pete', 'Kyenks', 'Blake'],
    ['Recover a stolen speaker rig', 'Escape the block', 'Lay low'],
    'A robbery wipes out Pete’s gear and the safety of the come-up evaporates fast.',
  ),
  ep(14, 'flowers', 'First Gig', 'DJ UV', 'Local bar', 'Flowers — Home City',
    2500, ['Gig board', 'Send-money-home'],
    ['Pete', 'DJ UV'],
    ['Land the bar residency', 'Win the dance floor', 'Wire money home'],
    'Pete’s first paid residency — small money, but the first cash he sends back to his mother.',
  ),
  ep(15, 'flowers', 'DJing Don’t Pay', 'Kyenks', 'Home City', 'Flowers — Home City',
    2500, ['Side-hustle system'],
    ['Pete', 'Kyenks', 'Blake'],
    ['Try three legit hustles', 'Realise it isn’t enough', 'Hear out Kyenks’ offer'],
    'Honest gigs can’t keep the lights on, and Kyenks dangles a faster, dirtier way to earn.',
  ),
  ep(16, 'flowers', 'The D-Boys', 'Kyenks', 'Trap house', 'Flowers — Home City',
    4000, ['Trap House (crib)', 'Stealth deal (Pusha P)'],
    ['Pete', 'Kyenks', 'The D-Boys'],
    ['Meet the D-Boys', 'Run a stealth delivery', 'Don’t get caught'],
    'Pete is introduced to the D-Boys and learns the sneaking/dealing loop — quiet money with loud consequences.',
  ),
  ep(17, 'flowers', 'House Party I', 'Blake', "Blake's yard", 'Flowers — Home City',
    3000, ['Pawn venue: House Party'],
    ['Pete', 'Blake', 'Ted'],
    ['Set up the rig', 'Keep the crowd hyped', 'Shut it down before the noise complaint'],
    'Pete throws his first house party — your first buildable Pawn-tier venue on the map.',
  ),
  ep(18, 'flowers', 'House Party II — Packed', 'Blake', 'The block', 'Flowers — Home City',
    5000, ['Crowd-control', 'Bar income'],
    ['Pete', 'Blake', 'Jasmine'],
    ['Upgrade the sound system', 'Manage the door money', 'Survive a gatecrash'],
    'Word spreads and the second party overflows — more money, more problems at the door.',
  ),
  ep(19, 'flowers', 'Project X', 'Ted', 'Abandoned estate', 'Flowers — Home City',
    8000, ['Reputation: Citywide'],
    ['Pete', 'Ted', 'Blake', 'Banda'],
    ['Promote the mega party', 'Headline the set', 'Escape the police raid'],
    'A Project-X-scale rager gets out of hand and is shut down by a full police raid.',
    { boss: false },
  ),
  ep(20, 'flowers', 'Heat in the Hood I', 'Kyenks', 'Home City', 'Flowers — Home City',
    6000, ['Wanted system'],
    ['Pete', 'Kyenks', 'The D-Boys'],
    ['Lose the tail', 'Move the stash', 'Pay off a cop'],
    'The raid puts heat on the whole block; Pete learns to manage a wanted level.',
  ),
  ep(21, 'flowers', 'Mega Twin Beef I', 'Banda', 'Weekend block party', 'Flowers — Home City',
    7000, ['DJ rivalry: The Twins'],
    ['Pete', 'Banda', 'The Twins'],
    ['Out-mix the first twin', 'Win the crowd vote'],
    'Twin rival DJs challenge Pete for the weekend; round one is a straight beat battle.',
  ),
  ep(22, 'flowers', 'Mega Twin Beef II', 'Banda', 'Rival venue', 'Flowers — Home City',
    9000, ['Sabotage mechanic'],
    ['Pete', 'Banda', 'The Twins'],
    ['Infiltrate the rivals’ party', 'Cut their power', 'Get out clean'],
    'The beef turns dirty — sabotage the twins’ own show before they sabotage yours.',
  ),
  ep(23, 'flowers', 'Mega Twin Beef III', 'Banda', 'Neutral ground', 'Flowers — Home City',
    12000, ['Crew: Banda'],
    ['Pete', 'Banda', 'The Twins'],
    ['Win the final sound clash', 'Settle the beef', 'Recruit Banda for good'],
    'The decider: a packed sound clash that ends the twin beef and locks Banda in as crew.',
    { boss: true },
  ),
  ep(24, 'flowers', 'Heat in the Hood II', 'Kyenks', 'Home City', 'Flowers — Home City',
    8000, ['Bail/lawyer system'],
    ['Pete', 'Kyenks', 'The D-Boys'],
    ['Break a friend out of holding', 'Burn the evidence', 'Reset the heat'],
    'The law closes in on the D-Boys and Pete has to clean up before the whole crew falls.',
  ),
  ep(25, 'flowers', 'House Party IV', 'Blake', 'Hilltop crib', 'Flowers — Home City',
    10000, ['Pawn venue upgrade'],
    ['Pete', 'Blake', 'Jasmine'],
    ['Headline the biggest house party yet', 'Hit the peak-drop combo', 'Protect the till'],
    'The fourth and biggest house party — the Pawn venue maxes out and the money gets serious.',
  ),
  ep(26, 'flowers', 'Someone Gets Shot', 'Blake', 'The party', 'Flowers — Home City',
    9000, ['Ambulance/triage minigame'],
    ['Pete', 'Blake', 'Jasmine'],
    ['Stop the fight', 'Get the victim to the ambulance', 'Calm the crowd'],
    'A party turns deadly when shots ring out, and Pete has to keep a friend alive until help arrives.',
    { boss: false },
  ),
  ep(27, 'flowers', 'DIP', 'Kyenks', 'Home City', 'Flowers — Home City',
    7000, ['Escape-driving'],
    ['Pete', 'Kyenks', 'Blake'],
    ['Scatter the crew', 'Ditch the weapons', 'Vanish before sunrise'],
    'After the shooting everyone has to disappear — a tense getaway across the whole region.',
  ),
  ep(28, 'flowers', 'SWAT 3-to-4 Stars', null, 'Home City', 'Flowers — Home City',
    11000, ['Play-as-anyone (WD-Legion)', 'Playable: D-Boys, OnDeKwa'],
    ['Pete', 'The D-Boys', 'OnDeKwa', 'SWAT'],
    ['Survive the SWAT raid as Pete', 'Switch to a D-Boy', 'Switch to OnDeKwa to escape'],
    'The signature mechanic unlocks: as the heat hits 4 stars you hot-swap between Pete, the D-Boys and OnDeKwa to survive the raid from multiple angles.',
    { boss: false },
  ),
  ep(29, 'flowers', 'Lights Out on the Block', 'Kyenks', 'Power substation', 'Flowers — Home City',
    13000, ['Blackout heists'],
    ['Pete', 'Kyenks', 'SubZ'],
    ['Kill the grid for the block', 'Run the blackout rave', 'Outsmart the pirate SubZ'],
    'Pete blacks out the whole block for an illegal rave and crosses paths with frequency-pirate SubZ from the wider war.',
  ),
  ep(30, 'flowers', 'Box Box Box', 'Kyenks', 'Underground gym', 'Flowers — Home City',
    12000, ['Boxing minigame', 'Stat: Stamina'],
    ['Pete', 'Kyenks'],
    ['Win three underground bouts', 'Bank the wager', 'Earn the gym’s respect'],
    'To toughen up (and pay a debt) Pete steps into the underground boxing ring.',
  ),
  ep(31, 'flowers', 'Ciani Loft', 'DJ UV', 'Ciani Village loft', 'Flowers — Home City',
    18000, ['Record deal offer', 'Crew: Jasmine'],
    ['Pete', 'DJ UV', 'Jasmine'],
    ['Play the loft session', 'Impress the label scout', 'Weigh the record offer'],
    'A market connection leads to a loft session where DJ UV lets Pete play and a label dangles a first record deal.',
  ),
  ep(32, 'flowers', 'Casablanca', 'Kyenks', 'Casablanca club', 'Flowers — Home City',
    25000, ['Bishop venue: Festival', 'Travel: Hearts'],
    ['Pete', 'Kyenks', 'The MDD Crew', 'Red Silence'],
    ['Headline Casablanca', 'Beat the MDD crew’s champion', 'Earn passage to the Royal School'],
    'The Flowers finale: a championship sound clash at Casablanca against the MDD crew — win it and the home region is yours as you leave for Hearts.',
    { boss: true },
  ),

  // ============================ ACT II — HEARTS (ROYAL MUSIC SCHOOL) ============================
  ep(33, 'hearts', 'Royal Welcome', 'The Dean', 'Royal Music School', 'Hearts — Royal Campus',
    20000, ['Campus map', 'Dorm crib'],
    ['Pete', 'The Dean'],
    ['Arrive on campus', 'Pass the entrance audition', 'Move into the dorm'],
    'Pete lands at the prestigious Royal Music School, a world away from the Flowers blocks.',
  ),
  ep(34, 'hearts', 'Two-Year Clock', 'The Dean', 'Dean’s office', 'Hearts — Royal Campus',
    22000, ['Scholarship meter'],
    ['Pete', 'The Dean'],
    ['Learn the scholarship terms', 'Set your major', 'Start the two-year countdown'],
    'The catch is made plain: the scholarship lasts two years and only the best survive the cut.',
  ),
  ep(35, 'hearts', 'Hangover Run', 'Blake', 'Dorms → Lecture hall', 'Hearts — Royal Campus',
    21000, ['Hangover-to-class (Bully) minigame'],
    ['Pete', 'Blake'],
    ['Wake up late and wrecked', 'Sprint across campus', 'Make it to class on time'],
    'After a welcome-week bender Pete has to drag himself to a 9am — the Bully-style get-to-class loop.',
  ),
  ep(36, 'hearts', 'The Rivals', 'The Dean', 'Recital hall', 'Hearts — Royal Campus',
    25000, ['Rival roster'],
    ['Pete', 'The Prodigy', 'Michelle'],
    ['Meet the elite students', 'Survive the ranking duel', 'Make an enemy and an ally'],
    'Pete meets the school’s gifted, vicious in-crowd — including the prodigy who runs the rankings.',
  ),
  ep(37, 'hearts', 'Jack the Beats 101', 'Michelle', 'Practice circle', 'Hearts — Royal Campus',
    28000, ['DJ-battle: the Circle (Naruto-style)'],
    ['Pete', 'Michelle'],
    ['Learn the battle circle', 'Counter three styles', 'Win your first ranked duel'],
    'Michelle teaches the core DJ-battle system — the head-to-head "circle" where you read and counter an opponent’s style.',
  ),
  ep(38, 'hearts', 'Give Her a Flower', 'Michelle', 'Campus gardens', 'Hearts — Royal Campus',
    30000, ['Romance system', 'Date venues'],
    ['Pete', 'Michelle'],
    ['Find the rare bloom', 'Give Michelle the flower', 'Walk her home'],
    'The romance beat at the heart of the act: Pete brings Michelle a flower from the gardens and the relationship system opens up.',
  ),
  ep(39, 'hearts', 'Battle of the Halls', 'The Dean', 'Great hall', 'Hearts — Royal Campus',
    34000, ['Ranked ladder'],
    ['Pete', 'The Prodigy'],
    ['Climb the hall ladder', 'Beat a top-ten student', 'Claim a practice room'],
    'Inter-hall competition begins and Pete starts climbing the official student ranking.',
  ),
  ep(40, 'hearts', 'Start a Business', 'Ted', 'Campus quad', 'Hearts — Royal Campus',
    36000, ['Business sim: merch/label'],
    ['Pete', 'Ted', 'Blake'],
    ['Help Ted launch the merch line', 'Run the first pop-up', 'Split the profit'],
    'Pete helps a friend start a campus business — your first taste of running a brand.',
  ),
  ep(41, 'hearts', 'After-Party Hopping', 'Banda', 'Old town', 'Hearts — Royal City',
    32000, ['Night-map', 'Stamina/intoxication balance'],
    ['Pete', 'Banda', 'Michelle'],
    ['Hit three after-parties in one night', 'Keep your buzz balanced', 'Get home standing'],
    'A city-wide night out chains the nightlife systems: shots, smoke, and knowing when to stop.',
  ),
  ep(42, 'hearts', 'Sneaking Out', 'Michelle', 'Dorms', 'Hearts — Royal Campus',
    30000, ['Curfew stealth'],
    ['Pete', 'Michelle'],
    ['Beat the dorm curfew', 'Avoid the wardens', 'Make the secret gig'],
    'To play an off-campus gig Pete has to sneak past curfew wardens — pure stealth.',
  ),
  ep(43, 'hearts', 'Sports with the Boys', 'Blake', 'Campus fields', 'Hearts — Royal Campus',
    33000, ['Minigames: basketball, soccer, rugby, cricket'],
    ['Pete', 'Blake', 'Ted'],
    ['Win the pick-up tournament', 'Pick a sport to main', 'Boost your stats'],
    'Downtime with the boys unlocks the sports minigame suite and the stat boosts they give.',
  ),
  ep(44, 'hearts', 'The Faculty’s Favourite', 'The Prodigy', 'Recital hall', 'Hearts — Royal Campus',
    40000, ['Rival: The Prodigy (boss-track)'],
    ['Pete', 'The Prodigy', 'The Dean'],
    ['Expose the rigged judging', 'Survive the prodigy’s set', 'Refuse to back down'],
    'Pete discovers the rankings are rigged for the faculty’s golden child and refuses to play along.',
  ),
  ep(45, 'hearts', 'Skate the Quad', 'Marko', 'Campus quad', 'Hearts — Royal Campus',
    34000, ['Skateboarding minigame'],
    ['Pete', 'Marko'],
    ['Clear the skate line', 'Beat Marko’s combo score', 'Tag the bell tower'],
    'Marko reappears and drags Pete into the skating scene — a fast traversal/trick minigame.',
  ),
  ep(46, 'hearts', 'Scoring', 'Banda', 'Royal City nightlife', 'Hearts — Royal City',
    35000, ['Social: charm/clout'],
    ['Pete', 'Banda', 'Michelle'],
    ['Work the room', 'Build clout without burning Michelle', 'Survive the love-triangle fallout'],
    'The social game heats up — clout, flirting, and the risk of blowing up the one real relationship Pete has.',
  ),
  ep(47, 'hearts', 'Beef with the Headliner', 'Michelle', 'City arena', 'Hearts — Royal City',
    45000, ['DJ-beef path'],
    ['Pete', 'Michelle', 'The Prodigy'],
    ['Answer the public callout', 'Win the arena clash', 'Humble the headliner'],
    'A touring headliner (the prodigy’s mentor) calls Pete out publicly and the beef goes citywide.',
  ),
  ep(48, 'hearts', 'The Politician Returns', 'Sister', 'Royal City', 'Hearts — Royal City',
    42000, ['Story flag: investigation'],
    ['Pete', 'Sister', 'The Politician'],
    ['Spot the politician’s motorcade', 'Tail him', 'Photograph the meeting'],
    'The man who killed Pete’s father turns up at the school as a wealthy patron — and Pete starts digging.',
    { boss: false },
  ),
  ep(49, 'hearts', 'Help Your Friends', 'Ted', 'Campus', 'Hearts — Royal Campus',
    40000, ['Crew loyalty meter'],
    ['Pete', 'Ted', 'Blake', 'Banda'],
    ['Bail Ted’s business out', 'Recover the stolen stock', 'Keep the crew together'],
    'Pete’s success starts to strain the crew; he has to choose to keep lifting his friends up.',
  ),
  ep(50, 'hearts', 'Spin the Bottle', 'Michelle', 'Dorm loft', 'Hearts — Royal Campus',
    44000, ['Relationship milestone'],
    ['Pete', 'Michelle'],
    ['Survive the party game', 'Have the honest conversation', 'Define the relationship'],
    'An intimate party game forces Pete and Michelle to get real about where they stand.',
  ),
  ep(51, 'hearts', 'Midnight Mashup', 'Banda', 'Underground club', 'Hearts — Royal City',
    55000, ['Genre-fusion combos'],
    ['Pete', 'Banda'],
    ['Fuse three genres live', 'Hit the perfect mashup', 'Win the underground crown'],
    'In a back-alley club Pete masters the genre-fusion combo that becomes his signature.',
  ),
  ep(52, 'hearts', 'Exam Week', 'The Dean', 'Examination hall', 'Hearts — Royal Campus',
    60000, ['Scholarship checkpoint'],
    ['Pete', 'The Dean', 'The Prodigy'],
    ['Pass the practical', 'Out-perform your rival', 'Keep the scholarship'],
    'The two-year clock hits its midpoint exam — fail and it’s over.',
  ),
  ep(53, 'hearts', 'The Rot Underneath', 'Michelle', 'Faculty wing', 'Hearts — Royal Campus',
    58000, ['Story flag: industry pipeline'],
    ['Pete', 'Michelle', 'The Politician'],
    ['Break into the records room', 'Find the donor ledger', 'Learn who really owns the school'],
    'Pete and Michelle uncover that the school is a feeder for a corrupt industry — and the politician’s name is all over it.',
    { boss: false },
  ),
  ep(54, 'hearts', 'Recital of Blood', 'The Prodigy', 'Grand recital', 'Hearts — Royal Campus',
    80000, ['Rival defeated', 'Bishop venue upgrade'],
    ['Pete', 'The Prodigy', 'Michelle'],
    ['Win the grand recital', 'Break the prodigy on stage', 'Refuse the faculty’s offer'],
    'Pete crushes the rigged grand recital and dethrones the prodigy — but turns down the poisoned prize.',
    { boss: true },
  ),
  ep(55, 'hearts', 'Scouted', 'Billionaire X', 'Royal City', 'Hearts — Royal City',
    150000, ['Knight venue: Nightclub', 'Travel: Diamonds'],
    ['Pete', 'Billionaire X', 'Michelle'],
    ['Take the meeting', 'Sign the development deal', 'Leave the school behind'],
    'A music-tech billionaire offers Pete the world; he leaves the Royal School — and Michelle — behind for the Diamonds.',
    { boss: true },
  ),

  // ============================ ACT III — DIAMONDS (BILLIONAIRE X) ============================
  ep(56, 'diamonds', 'Billionaire X', 'Billionaire X', 'X Tower', 'Diamonds — Gold City',
    100000, ['Penthouse crib', 'Private jet'],
    ['Pete', 'Billionaire X'],
    ['Tour the empire', 'Sign with X Industries', 'Get the penthouse keys'],
    'Pete is flown into the opulent Diamonds region and absorbed into Billionaire X’s music-tech empire.',
  ),
  ep(57, 'diamonds', 'Royal Audience', 'Billionaire X', 'The Palace', 'Diamonds — Gold City',
    120000, ['Royalty contacts'],
    ['Pete', 'Billionaire X', 'The Prince'],
    ['Perform for the royal court', 'Win the prince’s favour', 'Avoid the protocol traps'],
    'Pete plays a private set for desert royalty and learns the rules of a world built on money.',
  ),
  ep(58, 'diamonds', 'The Algorithm', 'Billionaire X', 'X Labs', 'Diamonds — Gold City',
    130000, ['Ability: trend-hijack'],
    ['Pete', 'Billionaire X'],
    ['Learn the recommendation engine', 'Game your own song to #1', 'See the cost'],
    'X reveals the empire runs on an app that decides what the world hears — and Pete learns to rig it.',
    { boss: false },
  ),
  ep(59, 'diamonds', 'High Stakes', 'The Prince', 'Sky casino', 'Diamonds — Gold City',
    160000, ['Casino/wager venue'],
    ['Pete', 'The Prince'],
    ['Win the high-roller set', 'Clear the marker', 'Bank the wager'],
    'A casino in the clouds where sets are wagered like poker hands and the buy-in is brutal.',
  ),
  ep(60, 'diamonds', 'Gold Chains', 'Billionaire X', 'Gold City', 'Diamonds — Gold City',
    180000, ['Luxury fleet'],
    ['Pete', 'Billionaire X'],
    ['Flex the new lifestyle', 'Lose the old crew’s calls', 'Notice who you’re becoming'],
    'The money is unreal — and Pete starts ignoring the calls from Blake, Banda, and home.',
  ),
  ep(61, 'diamonds', 'The Featherweight', 'Coach', 'Royal stadium', 'Diamonds — Gold City',
    170000, ['Pro boxing arc', 'Title belt'],
    ['Pete', 'Coach'],
    ['Win the title fight', 'Refuse to take a dive', 'Make a powerful enemy'],
    'A side path: Pete becomes a featherweight champion and refuses to throw a fixed fight, angering the wrong people.',
  ),
  ep(62, 'diamonds', 'Diamonds Are Forever', 'The Prince', 'Vault district', 'Diamonds — Gold City',
    220000, ['Heist crew'],
    ['Pete', 'The Prince', 'SubZ'],
    ['Case the vault', 'Pull the sound-cover heist', 'Split with the prince'],
    'Pete uses a live show as cover for a diamond-vault heist — his first truly criminal score.',
    { boss: false },
  ),
  ep(63, 'diamonds', 'Queen of the Night', 'Billionaire X', 'The Mirage', 'Diamonds — Gold City',
    260000, ['Queen venue: the Mirage'],
    ['Pete', 'Billionaire X'],
    ['Open the ultra-exclusive club', 'Curate the unforgettable night', 'Out-class every rival venue'],
    'Pete launches the Queen-tier venue — a one-of-one experience the whole region fights to get into.',
  ),
  ep(64, 'diamonds', 'The Industry Plant', 'Michelle', 'Gold City', 'Diamonds — Gold City',
    240000, ['Michelle returns'],
    ['Pete', 'Michelle', 'Billionaire X'],
    ['Reunite with Michelle', 'Hear her warning', 'Choose money or the truth'],
    'Michelle tracks Pete down to warn him X is grooming him as a disposable "plant" — and Pete doesn’t want to hear it.',
    { boss: false },
  ),
  ep(65, 'diamonds', 'Blood Money', 'Billionaire X', 'X Tower', 'Diamonds — Gold City',
    300000, ['Story flag: the source'],
    ['Pete', 'Billionaire X', 'The Politician'],
    ['Trace X’s backers', 'Find the politician’s signature', 'Confront X'],
    'The empire’s funding traces straight back to the politician who killed Pete’s father.',
    { boss: false },
  ),
  ep(66, 'diamonds', 'The Drill', 'The Prince', 'Desert dig site', 'Diamonds — Gold City',
    280000, ['Story flag: Komedians'],
    ['Pete', 'The Prince', 'The Komedians'],
    ['Investigate the mining rig', 'Survive first contact', 'Escape the dig'],
    'Strange outsiders — the Komedians — are drilling the planet; Pete stumbles into the wider war by accident.',
    { boss: false },
  ),
  ep(67, 'diamonds', 'Outrun the Storm', 'SubZ', 'Coast highway', 'Diamonds — Gold City',
    320000, ['Supercar racing tier'],
    ['Pete', 'SubZ'],
    ['Win the coastal grand prix', 'Lose the cartel chase', 'Deliver the package'],
    'A high-speed run along the diamond coast blends street racing with a getaway.',
  ),
  ep(68, 'diamonds', 'The Set-Up', 'Billionaire X', 'Gold City', 'Diamonds — Gold City',
    340000, ['Betrayal flag'],
    ['Pete', 'Billionaire X', 'The Politician'],
    ['Play the charity gala', 'Take the fall for X', 'Get burned'],
    'X uses Pete as the fall guy for a scandal, and Pete realises Michelle was right all along.',
    { boss: false },
  ),
  ep(69, 'diamonds', 'Burn the Tower', 'Michelle', 'X Tower', 'Diamonds — Gold City',
    400000, ['X Industries leverage'],
    ['Pete', 'Michelle', 'Billionaire X'],
    ['Steal the master servers', 'Expose the algorithm', 'Walk out with the empire’s keys'],
    'Pete turns the tables — stealing the empire’s core tech instead of getting buried by it.',
    { boss: false },
  ),
  ep(70, 'diamonds', 'Hostile Takeover', 'Pete', 'X Tower', 'Diamonds — Gold City',
    600000, ['Own X Industries'],
    ['Pete', 'Billionaire X'],
    ['Out-maneuver the board', 'Seize controlling shares', 'Dethrone X'],
    'No longer the protégé: Pete takes the empire from X in a cold, calculated boardroom coup.',
    { boss: false },
  ),
  ep(71, 'diamonds', 'The Prince’s Price', 'The Prince', 'The Palace', 'Diamonds — Gold City',
    700000, ['Royal alliance'],
    ['Pete', 'The Prince'],
    ['Strike the alliance', 'Pass the loyalty test', 'Pay the blood price'],
    'To hold the Diamonds, Pete must do something for the prince he can never take back.',
    { boss: false },
  ),
  ep(72, 'diamonds', 'Severance', 'Michelle', 'Gold City', 'Diamonds — Gold City',
    650000, ['Relationship: breaking point'],
    ['Pete', 'Michelle'],
    ['Choose the empire or Michelle', 'Live with it', 'Send her away safe'],
    'The person who could still save Pete from himself is the one he pushes away.',
    { boss: false },
  ),
  ep(73, 'diamonds', 'King of Diamonds', 'The Prince', 'Royal stadium', 'Diamonds — Gold City',
    900000, ['Diamonds region: owned'],
    ['Pete', 'The Prince', 'Billionaire X'],
    ['Headline the coronation gala', 'Crush the last rival house', 'Take the crown'],
    'Pete becomes the undisputed king of the Diamonds industry — rich, ruthless, and almost unrecognisable.',
    { boss: true },
  ),
  ep(74, 'diamonds', 'The Komedian Offer', 'The Komedians', 'Dig site', 'Diamonds — Gold City',
    800000, ['Story flag: the joke'],
    ['Pete', 'The Komedians'],
    ['Meet the Komedian envoy', 'Hear the offer', 'Refuse — for now'],
    'The Komedians, who outclass every musician, offer Pete a place in what comes after humanity’s "limits."',
    { boss: false },
  ),
  ep(75, 'diamonds', 'No Justice', 'Sister', 'Gold City courthouse', 'Diamonds — Gold City',
    850000, ['Story flag: verdict'],
    ['Pete', 'Sister', 'The Politician'],
    ['Fund the case against the politician', 'Watch it get thrown out', 'Make the decision'],
    'Pete spends a fortune to take the politician to court — and watches the system free him anyway.',
    { boss: false },
  ),
  ep(76, 'diamonds', 'The Last Good Thing', 'Blake', 'Gold City', 'Diamonds — Gold City',
    750000, ['Crew: final loyalty'],
    ['Pete', 'Blake', 'Banda'],
    ['Save Blake from X’s cleaners', 'Repay an old debt', 'Say a real goodbye'],
    'One last mission for the friends who started it all, before Pete leaves his old self behind for good.',
    { boss: false },
  ),
  ep(77, 'diamonds', 'Coronation', 'The Prince', 'The Palace', 'Diamonds — Gold City',
    1000000, ['Wealth tier: untouchable'],
    ['Pete', 'The Prince'],
    ['Accept the throne of the Diamonds', 'Name your price for Ongaku Prime', 'Set the plan'],
    'Crowned and cold, Pete sets his sights on the only thing left to take: Ongaku Prime.',
    { boss: false },
  ),
  ep(78, 'diamonds', 'Flight to the Capital', 'Pete', 'Gold City → Ongaku Prime', 'Diamonds — Gold City',
    1000000, ['Travel: Spades', 'King venue (locked preview)'],
    ['Pete', 'The Politician'],
    ['Board the jet', 'Cut every tie', 'Land in the Spades'],
    'Pete burns the last bridge and flies into the Spades to finish what the broadcast started.',
    { boss: true },
  ),

  // ============================ ACT IV — SPADES (REGICIDE) ============================
  ep(79, 'spades', 'Welcome to the Capital', 'The Politician', 'Ongaku Prime', 'Spades — Ongaku Prime',
    1000000, ['Capital map', 'Skyscraper HQ'],
    ['Pete', 'The Politician', 'General 24'],
    ['Enter Ongaku Prime', 'Take the meeting with the politician', 'Play your hand cold'],
    'Pete arrives in the gleaming, brutal capital — invited, smiling, by the very man he came to destroy.',
  ),
  ep(80, 'spades', 'The Kingmaker', 'The Politician', 'Senate spire', 'Spades — Ongaku Prime',
    1200000, ['Political leverage'],
    ['Pete', 'The Politician'],
    ['Infiltrate the inner circle', 'Learn how the king is made', 'Plant the first knife'],
    'To kill a king you first have to become one of his kingmakers; Pete plays the long con.',
    { boss: false },
  ),
  ep(81, 'spades', 'Underground Kingdom', 'SubZ', 'Sub-levels', 'Spades — Ongaku Prime',
    1300000, ['Castle venue: Underground Rave'],
    ['Pete', 'SubZ'],
    ['Open the Castle-tier rave', 'Win the underworld’s loyalty', 'Build a shadow army'],
    'Beneath the capital Pete builds the Castle — an underground rave empire that becomes his power base.',
  ),
  ep(82, 'spades', 'Everyone’s a DJ', 'General 24', 'Ongaku Prime', 'Spades — Ongaku Prime',
    1400000, ['Faction war: DJ24'],
    ['Pete', 'General 24', 'Sync'],
    ['Meet the DJ24 guardians', 'Refuse to be recruited', 'Mark them as obstacles'],
    'The guardians of DJ24 see what Pete is becoming and try to stop him — he sees them as in the way.',
    { boss: false },
  ),
  ep(83, 'spades', 'The Sick Deal', 'Red Silence', 'Dead zone', 'Spades — Ongaku Prime',
    1600000, ['Sick 52 alliance (uneasy)'],
    ['Pete', 'Red Silence'],
    ['Parley with the Sick 52', 'Trade favours', 'Keep your real plan hidden'],
    'Pete cuts a dangerous deal with Red Silence’s Sick 52 — each believing they’re using the other.',
    { boss: false },
  ),
  ep(84, 'spades', 'Mega Festival', 'Pete', 'Capital fairgrounds', 'Spades — Ongaku Prime',
    2000000, ['King venue: Mega Festival'],
    ['Pete', 'Banda', 'Michelle'],
    ['Build the King-tier festival', 'Sell out the capital', 'Broadcast to the whole planet'],
    'Pete throws a planet-wide mega-festival — the King venue — and turns the capital’s attention into a weapon.',
    { boss: false },
  ),
  ep(85, 'spades', 'The Comedians Land', 'General 24', 'Ongaku Prime skies', 'Spades — Ongaku Prime',
    2200000, ['Invasion event'],
    ['Pete', 'General 24', 'The Komedians'],
    ['Survive the Komedian assault', 'Improvise with DJ24', 'See how outmatched everyone is'],
    'The Komedians invade openly; for one night even Pete fights beside the people he plans to betray.',
    { boss: false },
  ),
  ep(86, 'spades', 'Command HQ', 'General 24', 'DJ24 spire', 'Spades — Ongaku Prime',
    2400000, ['Intel network'],
    ['Pete', 'General 24', 'Sync'],
    ['Set up a music command HQ', 'Gather intel on the Komedians', 'Quietly copy it for yourself'],
    'The musicians build a war room to study the enemy — and Pete siphons every secret for his own ends.',
    { boss: false },
  ),
  ep(87, 'spades', 'Gang Up', 'Sync', 'Genre districts', 'Spades — Ongaku Prime',
    2600000, ['Genre coalition'],
    ['Pete', 'Sync', 'Molly'],
    ['Unite the warring genres', 'Win their war chiefs over', 'Position yourself at the top'],
    'To beat the Komedians the genres must unite — and Pete makes sure they unite under him.',
    { boss: false },
  ),
  ep(88, 'spades', 'The Captured Ship', 'General 24', 'Crash site', 'Spades — Ongaku Prime',
    2800000, ['Komedian tech'],
    ['Pete', 'General 24', 'The Komedians'],
    ['Raid the abandoned Komedian ship', 'Recover the core', 'Decide who controls it'],
    'The one Komedian ship left behind holds tech that could change the war — and Pete intends to own it.',
    { boss: false },
  ),
  ep(89, 'spades', 'General Grievous', 'Pete', 'Underground Castle', 'Spades — Ongaku Prime',
    3200000, ['Title: General Grievous (Pete)'],
    ['Pete', 'SubZ', 'Red Silence'],
    ['Forge your war machine', 'Absorb rival crews', 'Become the thing they fear'],
    'The midpoint of the fall: Pete stops being a rising star and becomes a feared warlord of sound.',
    { boss: true },
  ),
  ep(90, 'spades', 'Betray the Guardians', 'Red Silence', 'DJ24 spire', 'Spades — Ongaku Prime',
    3600000, ['DJ24 weakened'],
    ['Pete', 'Red Silence', 'General 24', 'Sync'],
    ['Turn the Sick 52 loose on DJ24', 'Sabotage the guardians’ grid', 'Walk away clean'],
    'Pete springs his trap, using the Sick 52 to gut DJ24 from the inside.',
    { boss: false },
  ),
  ep(91, 'spades', 'Double Cross', 'Red Silence', 'Dead zone', 'Spades — Ongaku Prime',
    4000000, ['Sick 52 broken'],
    ['Pete', 'Red Silence', 'Bass Phantom'],
    ['Out-play Red Silence', 'Turn his own cards on him', 'Take the deck'],
    'With DJ24 crippled, Pete betrays his Sick 52 "allies" too and seizes the deck for himself.',
    { boss: true },
  ),
  ep(92, 'spades', 'The People’s Idol', 'Michelle', 'Capital plaza', 'Spades — Ongaku Prime',
    3800000, ['Mass influence'],
    ['Pete', 'Michelle'],
    ['Win the planet’s adoration', 'Use the crowd as cover', 'Ignore Michelle’s last plea'],
    'Pete becomes the planet’s beloved idol — and uses that love as armour while Michelle begs him to stop.',
    { boss: false },
  ),
  ep(93, 'spades', 'Storm the Senate', 'Pete', 'Senate spire', 'Spades — Ongaku Prime',
    4400000, ['Capital control'],
    ['Pete', 'The Politician', 'General 24'],
    ['Seize the senate spire', 'Disable the capital grid', 'Corner the politician'],
    'The endgame opens: Pete storms the seat of power and finally has the politician cornered.',
    { boss: false },
  ),
  ep(94, 'spades', 'Live on TV', 'Pete', 'Broadcast tower', 'Spades — Ongaku Prime',
    4800000, ['Story flag: full circle'],
    ['Pete', 'The Politician', 'Sister'],
    ['Hijack the planet-wide broadcast', 'Make the politician confess', 'Choose mercy or the mirror'],
    'Pete forces the politician to confess on the same live broadcast that killed his father — and chooses to become the mirror of the man he hated.',
    { boss: false },
  ),
  ep(95, 'spades', 'Riot', 'General 24', 'Ongaku Prime', 'Spades — Ongaku Prime',
    5200000, ['City-wide riot event'],
    ['Pete', 'General 24', 'Sync'],
    ['Ride the riot you started', 'Hold the streets', 'Let the old order burn'],
    'The confession detonates the capital into riots — exactly as Pete planned.',
    { boss: false },
  ),
  ep(96, 'spades', 'The Last Guardian', 'Sync', 'DJ24 ruins', 'Spades — Ongaku Prime',
    6000000, ['Boss: Sync'],
    ['Pete', 'Sync'],
    ['Face the last standing guardian', 'Win the impossible duel', 'Break the symbol of DJ24'],
    'Only Sync, the off-beat anomaly, stands between Pete and total control — and they finally clash.',
    { boss: true },
  ),
  ep(97, 'spades', 'The Komedian Bargain', 'The Komedians', 'Komedian ship', 'Spades — Ongaku Prime',
    6500000, ['Power: post-human sound'],
    ['Pete', 'The Komedians'],
    ['Accept the Komedians’ power', 'Pay the human price', 'Cross the final line'],
    'To win for good Pete takes the Komedians’ forbidden power — and gives up the last of what made him human.',
    { boss: false },
  ),
  ep(98, 'spades', 'Crown of Static', 'Pete', 'Senate spire', 'Spades — Ongaku Prime',
    8000000, ['Title: Z'],
    ['Pete', 'The Politician'],
    ['Take the capital’s crown', 'Rename yourself', 'Address the planet as its ruler'],
    'Pete sheds his name and becomes "Z," ruler of Ongaku Prime and the whole sound.',
    { boss: false },
  ),
  ep(99, 'spades', 'No Mercy', 'Z', 'Broadcast tower', 'Spades — Ongaku Prime',
    12000000, ['Point of no return'],
    ['Pete', 'The Politician', 'Michelle'],
    ['Deliver the politician’s end', 'Sever the last bond', 'Feel nothing'],
    'Z finally ends the politician — and the part of himself that ever wanted anything but power.',
    { boss: false },
  ),
  ep(100, 'spades', 'Regicide', 'Z', 'The Throne', 'Spades — Ongaku Prime',
    25000000, ['Boss: The King', 'Ending unlocked'],
    ['Pete', 'General 24', 'The King'],
    ['Storm the throne', 'Kill the king of Ongaku', 'Take the planet'],
    'The act’s namesake: Z commits regicide, ending the old king and claiming Planet Ongaku itself.',
    { boss: true },
  ),
  ep(101, 'spades', 'Long Live the Villain', 'Z', 'Ongaku Prime', 'Spades — Ongaku Prime',
    50000000, ['New Game+', 'Villain epilogue'],
    ['Z', 'Sync', 'The Komedians'],
    ['Address your conquered world', 'Set the stage for what comes next', 'Become the antagonist of the saga'],
    'The finale: the kid who wanted justice is now the villain the next heroes will have to stop — the door to the wider DJ24 saga.',
    { boss: true },
  ),
];

// ---- Selectors ----
export function getEpisodes() {
  return episodes;
}

export function getActsWithEpisodes() {
  return actOrder.map((key) => ({
    ...acts[key],
    episodes: episodes.filter((e) => e.act === key),
  }));
}

export function getEpisode(slug) {
  const idx = episodes.findIndex((e) => e.slug === slug);
  if (idx === -1) return null;
  const e = episodes[idx];
  return {
    ...e,
    actInfo: acts[e.act],
    art: acts[e.act].art,
    prev: idx > 0 ? episodes[idx - 1] : null,
    next: idx < episodes.length - 1 ? episodes[idx + 1] : null,
  };
}
